history.php
change icon, format date to string and dimensions of table
=> fixes in table attendance

history.php, lang/en/local_paperattendance.php, lang/es/local_paperattendance.php, locallib.php
=> fixes in table attendance 2

history.php, lang/en/local_paperattendance.php, lang/es/local_paperattendance.php, locallib.php
Capabilities for profesor and student and student not enrolled in course plus langs
=> fix in capabilities for history.php

classes/task/processpdf.php, lang/en/local_paperattendance.php, lang/es/local_paperattendance.php, version.php
=> function get name

db/access.php, forms/print_form.php, print.php, upload.php
ahora no seleccionar un módulo arroja error
=> fix WC-1895 jira

README.md, upload.php
=> Error on upload fixed by Cabane

print.php
Ahora al ir al futuro y no seleccionar un modulo, muestra correctamente los modulos pertenecientes a ese dia
=> fix on modules not shown

history.php, print.php
fix problem in date when upload list
=> fix date in sessionmodules

db/install.xml, db/upgrade.php, version.php
Added new camp "greyscale" to presence table
=> Added new camp "greyscale" to presence table

print.php
on checkbox click, hide other modules
=> fix on modules shown

print.php
=> correction

print.php
now it hides the modules according to current time
=> print modules fix

db/install.xml, db/upgrade.php, history.php, lang/en/local_paperattendance.php, lang/es/local_paperattendance.php, version.php
Added omegasync field to the presence table, plus the same field in history view to show if the student is synchronized or not with omega.
=> Added omegasync field to the presence table, plus the same field in

history.php, lang/en/local_paperattendance.php, lang/es/local_paperattendance.php, locallib.php, settings.php
=> createattendance and updateattendance

locallib.php, version.php
=> id in querys

locallib.php
=> fix query for getteacher in history. Jira WC-1910

db/install.xml, db/upgrade.php, history.php, lang/en/local_paperattendance.php, lang/es/local_paperattendance.php, version.php
Added name of the module to student view table
=> Added module to student view

upload.php
fix error, breadcrumbs in upload.php
=> fix breadcrumbs in upload.php

history.php, upload.php
create new var for the context system to save de files
=> FIX context system

cli/deletepdf.php, locallib.php, upload.php
delete pdf with unread qr, rotate function comented beacuse unused. And added png deleting in cli for the unread folder
=> Optimize qr reading, delimit clipping qr bottom, delete qr not used,

upload.php
=> delete pdf in unread folder, when upload with missing pages

history.php, locallib.php
=> Added Omega column to the attendance table for teachers

db/upgrade.php, discussion.php, forms/response_form.php, forms/reviewattendance_form.php, history.php, lang/en/local_paperattendance.php, lang/es/local_paperattendance.php, version.php
There was created discussion table and there was added description field
to session table. There are a few things missing to finish.
=> Now students can request a review of his attendance

discussion.php, history.php, lang/en/local_paperattendance.php, lang/es/local_paperattendance.php, settings.php, summary.php, version.php
back to course button was added to attendance summary view
=> Max time to request a review of a attendance was added as a setting

export.php, forms/export_form.php, history.php, lang/en/local_paperattendance.php, lang/es/local_paperattendance.php, locallib.php
And little change on paperattendance_returnattendancedescription()
function was made.
=> Export form was created

discussion.php, summary.php
And a row counter was added in summary table
=> pagination was added to discussions view

export.php, summary.php
And change summary to only show students enrolled by CFG enrollment
method
=> Excel export fix

discussion.php, history.php, summary.php
And timestamps added to discussions
=> Unsynchronized sessions doesn't sum to sessions held now

export.php, locallib.php
There was added a tabs parameter to exporttoexcel function
=> new tab summary was added to excel export

ajax/ajaxquerys.php
this for the admin and secretary view
=> fix printsearch now teachers come from cfg->enrolmethods

ajax/ajaxquerys.php, db/install.xml, db/upgrade.php, export.php, lang/en/local_paperattendance.php, lang/es/local_paperattendance.php, locallib.php, missingpages.php, printsearch.php, quickprint.php, settings.php, summary.php, version.php
Fix moodlecloud - Add settings with role parameters to use in plugin
fix viewback button
Remove save button after save missing page
Page style update for the new theme
New table to save missing pages reference
=> theme change

printsearch.php
Saving list cart items in localstorage
=> Fix list cart
